"""database creation

Revision ID: 62cdd570a1d2
Revises: 
Create Date: 2023-07-11 10:53:52.500388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62cdd570a1d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('amount', sa.Integer(), nullable=False),
        sa.Column('next_increase', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(), nullable=False),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('salary_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['salary_id'], ['salary.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('salary')
    # ### end Alembic commands ###
